### PR TITLE
Added chips for tags, code completion support in ace editor and snippet support

### PR DESCRIPTION
**Pull request by rahulyadav170923**
Completed #8  and  #3

### CODE REVIEW

**Comment by championswimmer** [comment]
@omerjerk please check this

@rahulyadav170923 please add screenshots for UI changes

**Comment by rahulyadav170923** [comment]
screen shot 2017-05-27 at 2 41 14 pm

**Comment by omerjerk** [comment]
@rahulyadav170923 Remove the tag image. Rest all looks perfect.

**Comment by rahulyadav170923** [comment]
@omerjerk solved #8 #9 #1 in this pull request.

**Comment by championswimmer** [comment]
@rahulyadav170923 do not solve multiple issues on same PR in future please. 
For this one, if it gets merged, when claiming bounty, claim for the sum total amount of all issue bounties in a single claim.

**Pull request merged**
