### PR TITLE
SVG/Vectorised logo of HackerBlocks

### PR DESCRIPTION
**Pull request by ArushiSinghal**
@prateek27 
Issue #40

### CODE REVIEW

**Comment by championswimmer** [comment]
@prateek27 
this was incomplete. the svg image is added, but it has not been actually used in the navbar

**Comment by championswimmer** [comment]
@ArushiSinghal can you make necessary changes and make new PR ?

**Comment by ArushiSinghal** [comment]
@championswimmer @prateek27  I have added 4 logos. Please check logo_4.svg
https://github.com/coding-blocks/hacker-blocks/blob/master/public/images/logo_4.svg
 I think the other logos which I have added is for the image described in the issue.
https://github.com/coding-blocks/hacker-blocks/issues/40

Link to all for images:
https://github.com/coding-blocks/hacker-blocks/blob/master/public/images/logo_1.svg
https://github.com/coding-blocks/hacker-blocks/blob/master/public/images/logo_2.svg
https://github.com/coding-blocks/hacker-blocks/blob/master/public/images/logo_3.svg
https://github.com/coding-blocks/hacker-blocks/blob/master/public/images/logo_4.svg

**Comment by championswimmer** [comment]
yeah use logo_4

**Comment by championswimmer** [comment]
you need to **ACTUALLY USE THAT IN THE NAVBAR**

**Comment by omerjerk** [comment]
Let know if I should close the other one.

**Comment by ArushiSinghal** [comment]
@championswimmer should I remove other logos?

**Pull request merged**
