### PR TITLE
#40 svg/vectorised logo added

### PR DESCRIPTION
**Pull request by shubhamvashisht**

### CODE REVIEW

**Comment by shubhamvashisht** [comment]
@prateek27  The svg logo that i added is lite and of less size.

**Comment by shubhamvashisht** [comment]
@prateek27 please review

**Comment by omerjerk** [comment]
@shubhamvashisht Please post the screenshot of the svg.

**Comment by shubhamvashisht** [comment]
img_20170702_001127

@omerjerk 
Github doesn't support .svg images in comments. So took screenshot of logo and posted. Also the .svg image is already there in this PR and you can preview there. Its exactly like the image given in issue.
Thanks.

**Pull request closed without merging**
