### PR TITLE
Changed /practice to /dcb (Daily Code Bytes) and /practice-section to /practice

### LINKED ISSUE #28: move `/practice` route to `/dcb` route (for Daily Code Bytes) and `/practice-section` to `/practice`

### PR DESCRIPTION
**Pull request by prateekiiest**
@championswimmer  reviews pls!

Fixes #28

### CODE REVIEW

**Comment by prateekiiest** [comment]
Changing practice-session to practice

**Comment by championswimmer** [comment]
Can you not make so many commits ? You should clone and do it on your PC. 

I am sure the objective of Github is for hosting code and not to use as a code editor.

**Comment by prateekiiest** [comment]
Yes, I could have squashed all the commits

**Comment by championswimmer** [comment]
Anyway we can squash when we merge. 
Waiting on @omerjerk to review this.

**Comment by omerjerk** [comment]
This has been solved already. :)

**Pull request closed without merging**
