### PR TITLE
Added scroll behaviour in online user list

### LINKED ISSUE #25: Bug Report: Online users list is not scrollable
I have tested it in chrome and it is not scrolling. 

screen shot 2017-06-15 at 4 53 14 pm

### PR DESCRIPTION
**Pull request by anu0012**
Fixes #25

### CODE REVIEW

**Comment by omerjerk** [comment]
May I know the reason for the commit message "Create template.hbs" ?

**Comment by anu0012** [comment]
@omerjerk I have created a new pull request with updated message. Please check it.

**Comment by omerjerk** [comment]
Okay. Just in case you fall into the same issue again, please read about "git amend" on internet. This command is used to modify last commit.

**Comment by anu0012** [comment]
Thanks. I will take care of this in future.

**Pull request closed without merging**
